process.env.DB_NAME = process.env.DB_NAME || "test_db"
process.env.DB_USER = process.env.DB_USER || "test_user"
process.env.DB_PASSWORD = process.env.DB_PASSWORD || "test_password"
process.env.DB_HOST = process.env.DB_HOST || "localhost"
process.env.JWT_SECRET = process.env.JWT_SECRET || "test-secret"
process.env.LOG_LEVEL = "silent"
