sonar.projectKey=zainabusman22_cohort-9-mern-11414-zainab
sonar.organization=zainabusman22

sonar.sources=backend,frontend/src
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,frontend/src/vite-env.d.ts
sonar.sourceEncoding=UTF-8
